version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn RCC_Workshop_Docker.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"